[build]
  command = "yarn run build"
  functions = "functions"
  publish = "dist"

[dev]
  command = "yarn dev:vite" # Command to start your dev server
  port = 8888 # Port that the dev server will be accessible on
  targetPort = 3000 # Port of target app server
  # publish = "dist" # If you use a _redirect file, provide the path to your static content folder
  # jwtRolePath = "app_metadata.authorization.roles" # Object path we should look for role values for JWT based redirects
  # autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
